version: "3"

services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    networks:
      - "shared-network"
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000
    networks:
      - "shared-network"
    depends_on:
      - api
    stdin_open: true
    tty: true
  api:
    build: ./server
    restart: unless-stopped
    env_file: ./server/.env.production
    ports:
      - "5000:5000"
    networks:
      - "shared-network"
networks:
  shared-network: