version: "3"

services:
  client:
    build: ./client
    container_name: lukoil_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./app/node_modules
    networks:
      - "shared-network"
    depends_on:
      - server
    stdin_open: true
    tty: true
  server:
    build: ./server
    container_name: lukoil_backend
    restart: unless-stopped
    env_file: ./server/.env.production
    ports:
      - "5000:5000"
    networks:
      - "shared-network"
networks:
  shared-network: